version: '3'
services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zimablue
      MYSQL_DATABASE: library
      MYSQL_USER: root
      MYSQL_PASSWORD: zimablue
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
  backend:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  db_data:
